@extends('layouts.app')

@section('title', 'Dashboard | XAUUSD Trading Journal')

@section('content')
    <div class="mb-8"><p class="text-sm font-medium text-amber-300">XAUUSD price action analytics</p><h1 class="mt-1 text-3xl font-bold tracking-tight text-white">Trading dashboard</h1><p class="mt-2 text-sm text-slate-400">Performance is calculated from the currently filtered journal trades.</p></div>

    <section class="mb-8 rounded-2xl border border-white/10 bg-slate-900/70 p-4 sm:p-6">
        <form method="GET" class="space-y-5">
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <div class="space-y-3"><label for="period" class="journal-label">Date Range</label><select name="period" id="period" class="journal-input"><option value="">All time</option>@foreach(['today' => 'Today', 'yesterday' => 'Yesterday', 'this_week' => 'This Week', 'last_week' => 'Last Week', 'this_month' => 'This Month', 'last_month' => 'Last Month', 'this_year' => 'This Year', 'custom' => 'Custom Range'] as $value => $label)<option value="{{ $value }}" @selected(($filters['period'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><div id="custom-date-fields" class="grid gap-3" @if(($filters['period'] ?? '') !== 'custom') hidden @endif><label for="date_from" class="journal-label">Start Date<input type="date" name="date_from" id="date_from" value="{{ $filters['date_from'] ?? '' }}" class="journal-input mt-1" @disabled(($filters['period'] ?? '') !== 'custom')></label><label for="date_to" class="journal-label">End Date<input type="date" name="date_to" id="date_to" value="{{ $filters['date_to'] ?? '' }}" class="journal-input mt-1" @disabled(($filters['period'] ?? '') !== 'custom')></label></div></div>
                <label for="direction" class="journal-label">Direction<select name="direction" id="direction" class="journal-input mt-1"><option value="">All directions</option><option value="buy" @selected(($filters['direction'] ?? '') === 'buy')>BUY</option><option value="sell" @selected(($filters['direction'] ?? '') === 'sell')>SELL</option></select></label>
                <label for="timeframe" class="journal-label">Timeframe<select name="timeframe" id="timeframe" class="journal-input mt-1"><option value="">All timeframes</option>@foreach(['15m', '30m', '1h', '4h'] as $timeframe)<option value="{{ $timeframe }}" @selected(($filters['timeframe'] ?? '') === $timeframe)>{{ strtoupper($timeframe) }}</option>@endforeach</select></label>
                <label for="trade_reason_id" class="journal-label">Price Action Setup<select name="trade_reason_id" id="trade_reason_id" class="journal-input mt-1"><option value="">All setups</option>@foreach($reasons as $reason)<option value="{{ $reason->id }}" @selected((string) ($filters['trade_reason_id'] ?? '') === (string) $reason->id)>{{ $reason->name }}</option>@endforeach</select></label>
                <label for="entry_type_id" class="journal-label">Entry Type<select name="entry_type_id" id="entry_type_id" class="journal-input mt-1"><option value="">All entry types</option>@foreach($entryTypes as $type)<option value="{{ $type->id }}" @selected((string) ($filters['entry_type_id'] ?? '') === (string) $type->id)>{{ $type->name }}</option>@endforeach</select></label>
                <label for="market_condition" class="journal-label">Market Condition<select name="market_condition" id="market_condition" class="journal-input mt-1"><option value="">All market conditions</option>@foreach(['trending', 'ranging', 'consolidating', 'volatile', 'choppy', 'clean'] as $condition)<option value="{{ $condition }}" @selected(($filters['market_condition'] ?? '') === $condition)>{{ ucfirst($condition) }}</option>@endforeach</select></label>
                <label for="trade_mistake_id" class="journal-label">Trade Mistake<select name="trade_mistake_id" id="trade_mistake_id" class="journal-input mt-1"><option value="">All mistakes</option>@foreach($mistakes as $mistake)<option value="{{ $mistake->id }}" @selected((string) ($filters['trade_mistake_id'] ?? '') === (string) $mistake->id)>{{ $mistake->name }}</option>@endforeach</select></label>
                <label for="status" class="journal-label">Result<select name="status" id="status" class="journal-input mt-1"><option value="">All results</option>@foreach(['open', 'win', 'loss', 'breakeven'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ strtoupper($status) }}</option>@endforeach</select></label>
            </div>
            <div class="flex flex-col gap-3 sm:flex-row sm:justify-end"><button class="rounded-lg bg-amber-400 px-5 py-2.5 text-sm font-semibold text-slate-950 hover:bg-amber-300">Apply Filters</button><a href="{{ route('dashboard') }}" class="rounded-lg border border-white/15 px-5 py-2.5 text-center text-sm font-semibold text-slate-300 hover:bg-white/10">Reset Filters</a></div>
        </form>
        @if($activeFilters !== [])<div class="mt-5 border-t border-white/10 pt-4"><div class="flex flex-col gap-3 sm:flex-row sm:items-center"><p class="text-sm font-semibold text-white">Active Filters</p><div class="flex flex-wrap gap-2">@foreach($activeFilters as $label => $value)<span class="rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-slate-200">{{ $label }}: {{ $value }}</span>@endforeach</div><a href="{{ route('dashboard') }}" class="text-sm font-semibold text-amber-300 hover:text-amber-200 sm:ml-auto">Clear All Filters</a></div></div>@endif
    </section>

    @if($analytics['kpis']['trades'] === 0)
        <div class="rounded-2xl border border-dashed border-white/15 bg-slate-900/50 px-6 py-16 text-center"><h2 class="text-lg font-semibold text-white">No trades found for the selected filters.</h2><p class="mt-2 text-sm text-slate-400">Change your filters or add a new XAUUSD trade.</p><a href="{{ route('trades.create') }}" class="mt-5 inline-flex rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Add trade</a></div>
    @else
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
            @foreach([['Total trades', $analytics['kpis']['trades'], 'text-white'], ['Winning trades', $analytics['kpis']['wins'], 'text-emerald-300'], ['Losing trades', $analytics['kpis']['losses'], 'text-rose-300'], ['Breakeven trades', $analytics['kpis']['breakevens'], 'text-slate-300'], ['Win rate', $analytics['kpis']['win_rate'] === null ? '—' : number_format($analytics['kpis']['win_rate'], 1).'%', 'text-amber-200'], ['Net P/L', '$'.number_format($analytics['kpis']['net_profit_loss'], 2), $analytics['kpis']['net_profit_loss'] >= 0 ? 'text-emerald-300' : 'text-rose-300'], ['Average R:R', $analytics['kpis']['average_risk_reward'] === null ? '—' : '1:'.number_format($analytics['kpis']['average_risk_reward'], 2), 'text-white'], ['Profit factor', $analytics['kpis']['profit_factor'] === null ? '—' : number_format($analytics['kpis']['profit_factor'], 2), 'text-white'], ['Total risk', '$'.number_format($analytics['kpis']['total_risk'], 2), 'text-amber-200'], ['Avg winning trade', $analytics['kpis']['average_winning_trade'] === null ? '—' : '$'.number_format($analytics['kpis']['average_winning_trade'], 2), 'text-emerald-300'], ['Avg losing trade', $analytics['kpis']['average_losing_trade'] === null ? '—' : '$'.number_format($analytics['kpis']['average_losing_trade'], 2), 'text-rose-300']] as [$label, $value, $color])<article class="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><p class="metric-label">{{ $label }}</p><p class="mt-2 text-2xl font-bold {{ $color }}">{{ $value }}</p></article>@endforeach
        </div>

        <section class="mt-8"><h2 class="mb-4 text-xl font-semibold text-white">Performance highlights</h2><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['bestSetup' => 'Best setup', 'worstSetup' => 'Worst setup', 'bestTimeframe' => 'Best timeframe', 'worstTimeframe' => 'Worst timeframe', 'bestWeekday' => 'Best weekday', 'worstWeekday' => 'Worst weekday', 'bestEntryType' => 'Best entry type'] as $key => $label)@php($highlight = $analytics['highlights'][$key])<article class="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><p class="metric-label">{{ $label }}</p><p class="mt-2 font-semibold text-white">{{ $highlight['name'] ?? '—' }}</p><p class="mt-1 text-sm {{ ($highlight['net_profit_loss'] ?? 0) >= 0 ? 'text-emerald-300' : 'text-rose-300' }}">{{ $highlight ? '$'.number_format($highlight['net_profit_loss'], 2) : 'No data' }}</p></article>@endforeach</div></section>

        <section class="mt-8 grid gap-6 xl:grid-cols-2"><div class="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 class="text-lg font-semibold text-white">Cumulative P/L</h2><p class="mt-1 text-sm text-slate-400">Closed trades in chronological order.</p><canvas id="equity-chart" class="mt-5 h-64 w-full"></canvas></div><div class="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 class="text-lg font-semibold text-white">Daily P/L</h2><p class="mt-1 text-sm text-slate-400">Net P/L by trade date.</p><canvas id="daily-chart" class="mt-5 h-64 w-full"></canvas></div><div class="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 class="text-lg font-semibold text-white">Win / loss distribution</h2><canvas id="results-chart" class="mt-5 h-64 w-full"></canvas></div><div class="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 class="text-lg font-semibold text-white">P/L by timeframe</h2><canvas id="timeframes-chart" class="mt-5 h-64 w-full"></canvas></div><div class="rounded-2xl border border-white/10 bg-slate-900/70 p-5 xl:col-span-2"><h2 class="text-lg font-semibold text-white">P/L by setup</h2><canvas id="setups-chart" class="mt-5 h-64 w-full"></canvas></div></section>

        @if($analytics['insights']->isNotEmpty())<section class="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><h2 class="text-lg font-semibold text-amber-100">Data-driven insights</h2><ul class="mt-3 space-y-2 text-sm text-amber-50/80">@foreach($analytics['insights'] as $insight)<li>{{ $insight }}</li>@endforeach</ul></section>@endif

        <section class="mt-8 space-y-8"><div><h2 class="mb-4 text-xl font-semibold text-white">Performance by timeframe</h2>@include('dashboard._performance-table', ['rows' => $analytics['timeframes'], 'label' => 'Timeframe', 'showProfitFactor' => true])</div><div><h2 class="mb-4 text-xl font-semibold text-white">Performance by price action setup</h2>@include('dashboard._performance-table', ['rows' => $analytics['setups'], 'label' => 'Setup', 'showProfitFactor' => true])</div><div><h2 class="mb-4 text-xl font-semibold text-white">Performance by entry type</h2>@include('dashboard._performance-table', ['rows' => $analytics['entryTypes'], 'label' => 'Entry type'])</div><div><h2 class="mb-4 text-xl font-semibold text-white">Performance by market condition</h2>@include('dashboard._performance-table', ['rows' => $analytics['conditions'], 'label' => 'Market condition'])</div><div><h2 class="mb-4 text-xl font-semibold text-white">Performance by weekday</h2>@include('dashboard._performance-table', ['rows' => $analytics['weekdays'], 'label' => 'Weekday'])</div><div><h2 class="mb-4 text-xl font-semibold text-white">BUY vs SELL</h2>@include('dashboard._performance-table', ['rows' => $analytics['directions'], 'label' => 'Direction'])</div></section>

        <section class="mt-8"><h2 class="mb-4 text-xl font-semibold text-white">Trade mistake analysis</h2><div class="overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70"><table class="min-w-full text-left text-sm"><thead class="border-b border-white/10 bg-white/5 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Mistake</th><th class="px-4 py-3">Occurrences</th><th class="px-4 py-3">Net P/L</th><th class="px-4 py-3">Win rate</th></tr></thead><tbody class="divide-y divide-white/10">@foreach($analytics['mistakes'] as $row)<tr><td class="px-4 py-3 font-medium text-white">{{ $row['name'] }}</td><td class="px-4 py-3 text-slate-300">{{ $row['trades'] }}</td><td class="px-4 py-3 {{ $row['net_profit_loss'] >= 0 ? 'text-emerald-300' : 'text-rose-300' }}">${{ number_format($row['net_profit_loss'], 2) }}</td><td class="px-4 py-3 text-slate-300">{{ $row['win_rate'] === null ? '—' : number_format($row['win_rate'], 1).'%' }}</td></tr>@endforeach</tbody></table></div></section>

        <section class="mt-8"><h2 class="mb-4 text-xl font-semibold text-white">Daily performance</h2><div class="overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70"><table class="min-w-full text-left text-sm"><thead class="border-b border-white/10 bg-white/5 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Trades</th><th class="px-4 py-3">Wins</th><th class="px-4 py-3">Losses</th><th class="px-4 py-3">Net P/L</th></tr></thead><tbody class="divide-y divide-white/10">@foreach($analytics['daily'] as $day)<tr><td class="px-4 py-3 text-white">{{ $day['date'] }}</td><td class="px-4 py-3 text-slate-300">{{ $day['trades'] }}</td><td class="px-4 py-3 text-emerald-300">{{ $day['wins'] }}</td><td class="px-4 py-3 text-rose-300">{{ $day['losses'] }}</td><td class="px-4 py-3 {{ $day['net_profit_loss'] >= 0 ? 'text-emerald-300' : 'text-rose-300' }}">${{ number_format($day['net_profit_loss'], 2) }}</td></tr>@endforeach</tbody></table></div></section>
    @endif
@endsection

@push('scripts')
<script>
const periodSelect = document.getElementById('period');
const customDateFields = document.getElementById('custom-date-fields');
const startDateInput = document.getElementById('date_from');
const endDateInput = document.getElementById('date_to');
const updateCustomDateFields = () => { const isCustom = periodSelect.value === 'custom'; customDateFields.hidden = !isCustom; [startDateInput, endDateInput].forEach((input) => { input.disabled = !isCustom; input.required = isCustom; }); if (isCustom) { endDateInput.min = startDateInput.value; } };
const validateCustomDates = () => { endDateInput.setCustomValidity(startDateInput.value && endDateInput.value && endDateInput.value < startDateInput.value ? 'End Date must be on or after Start Date.' : ''); };
periodSelect.addEventListener('change', updateCustomDateFields); startDateInput.addEventListener('change', () => { updateCustomDateFields(); validateCustomDates(); }); endDateInput.addEventListener('change', validateCustomDates); updateCustomDateFields(); validateCustomDates();
const drawLineChart = (canvasId, points) => { const canvas = document.getElementById(canvasId); if (!canvas || !points.length) return; const context = canvas.getContext('2d'); const width = canvas.width = canvas.clientWidth * devicePixelRatio; const height = canvas.height = canvas.clientHeight * devicePixelRatio; context.scale(devicePixelRatio, devicePixelRatio); const displayWidth = canvas.clientWidth; const displayHeight = canvas.clientHeight; const values = points.map((point) => point.value); const min = Math.min(0, ...values); const max = Math.max(0, ...values); const range = max - min || 1; const padding = 24; context.strokeStyle = '#334155'; context.beginPath(); context.moveTo(padding, padding); context.lineTo(padding, displayHeight - padding); context.lineTo(displayWidth - padding, displayHeight - padding); context.stroke(); context.strokeStyle = '#fbbf24'; context.lineWidth = 2; context.beginPath(); points.forEach((point, index) => { const x = padding + ((displayWidth - padding * 2) * index / Math.max(points.length - 1, 1)); const y = displayHeight - padding - ((point.value - min) / range) * (displayHeight - padding * 2); index ? context.lineTo(x, y) : context.moveTo(x, y); }); context.stroke(); };
const drawBarChart = (canvasId, source) => { const points = Array.isArray(source) ? source : Object.entries(source).map(([label, value]) => ({label, value})); const canvas = document.getElementById(canvasId); if (!canvas || !points.length) return; const context = canvas.getContext('2d'); canvas.width = canvas.clientWidth * devicePixelRatio; canvas.height = canvas.clientHeight * devicePixelRatio; context.scale(devicePixelRatio, devicePixelRatio); const width = canvas.clientWidth; const height = canvas.clientHeight; const padding = 28; const baseline = height / 2; const max = Math.max(1, ...points.map((point) => Math.abs(point.value))); const barWidth = Math.max(12, (width - padding * 2) / points.length - 12); points.forEach((point, index) => { const barHeight = Math.abs(point.value) / max * (height / 2 - padding); const x = padding + index * ((width - padding * 2) / points.length) + 6; const y = point.value >= 0 ? baseline - barHeight : baseline; context.fillStyle = point.value >= 0 ? '#34d399' : '#fb7185'; context.fillRect(x, y, barWidth, barHeight); }); context.strokeStyle = '#334155'; context.beginPath(); context.moveTo(padding, baseline); context.lineTo(width - padding, baseline); context.stroke(); };
drawLineChart('equity-chart', {{ Js::from($analytics['charts']['equity']) }}); drawLineChart('daily-chart', {{ Js::from($analytics['charts']['daily']) }}); drawBarChart('results-chart', {{ Js::from($analytics['charts']['results']) }}); drawBarChart('timeframes-chart', {{ Js::from($analytics['charts']['timeframes']) }}); drawBarChart('setups-chart', {{ Js::from($analytics['charts']['setups']) }});
</script>
@endpush
